### ISSUE TITLE
Feature: Hide stacktrace

### ISSUE THREAD

**Issue by ihalaij1** [Aalto-LeTech/python-grader-utils#2]
Could we have an option to hide stacktrace so the students can't see some of the exercise model answer on AssertionError.

**Comment by matiaslindgren** [comment]
@ihalaij1 
This is now possible in v2.7, see the updated [config](https://github.com/Aalto-LeTech/python-grader-utils/blob/v2.7/graderutils/test_config.yaml#L31-L34) for an example.
