### ISSUE TITLE
Support for colored text in assertionErrors

### ISSUE THREAD

**Issue by ihalaij1** [Aalto-LeTech/python-grader-utils#9]
Opiskelijalle näkyvään palautekenttään pitäisi saada näkyviin html:llä väritettyä tekstiä, joka näyttää merkkijonojen eroavaisuudet.

**Comment by matiaslindgren** [comment]
Tässä yksi vaihtoehto:
https://github.com/Aalto-LeTech/python-grader-utils/tree/5d351506db3547e1ec5e77a90431adcf654d82f9/examples/05_string_similarity_highlight

Tuo tosin toimii vasta kun utilsista on julkaistu versio 3 ja se on saatavilla graderi-imagessa.
